#!/usr/bin/env bash

apt-get update -y
apt-get install -y nginx

sed -i "/listen 80 default_server;/a \ \ \ \ add_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default

service nginx restart
