#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By HTTP header containing the hostname

sudo apt-get update -y
sudo apt-get install -y nginx

if ! sudo grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sudo sed -i '/listen 80 default_server;/a\\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
fi

sudo service nginx restart || sudo service nginx start